### ISSUE TITLE
ALSA errors

### ISSUE THREAD

**Issue by nojvspine** [jackplus-xyz/player-one.nvim#17]
When opening any file with nvim with this plugin, ALSA errors popup saying `an error occured on output stream: A backend-specific error has occured: ALSA function 'poll' failed with error 'Unknown errno (-4)'`

![Image](https://github.com/user-attachments/assets/cf95913b-a43a-460f-b11b-72b02b68835a)

Setup:
 - Arch Linux
 - Nvim 0.11.0
 - Lazy.nvim 11.17.1
 - Player-One commit c34d07d

Steps to reproduce:
 1. Install player-one.nvim through Lazy with default spec
 2. Open any file
 3. Errors popup

**Comment by nojvspine** [comment]
I have pipewire-alsa, quick test works with the rest audio on the system.
pactl info
```
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 107
Tile Size: 65472
User Name: zenn
Host Name: zebrahost30
Server Name: PulseAudio (on PipeWire 1.4.6)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_75_00.6.HiFi__Speaker__sink
Default Source: alsa_input.pci-0000_75_00.6.HiFi__Mic1__source
Cookie: 52a1:e3a3
```
aplay -l
```
**** List of PLAYBACK Hardware Devices ****
card 0: NVidia [HDA NVidia], device 3: HDMI 0 [VA1916wSERIES]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: NVidia [HDA NVidia], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: NVidia [HDA NVidia], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: NVidia [HDA NVidia], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Generic [HD-Audio Generic], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Generic_1 [HD-Audio Generic], device 0: ALC245 Analog [ALC245 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
cat /proc/asound/cards
```
 0 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xb9000000 irq 53
 1 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xb98c8000 irq 98
 2 [Generic_1      ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xb98c0000 irq 99
 3 [acp6x          ]: acp6x - acp6x
                      RB-NitroANV15_41-V1.06-Sportage_RBH
```

**Comment by jackplus-xyz** [comment]
#27 should fix it. Please update the plugin and let me know.

**Comment by nojvspine** [comment]
Yep, it's fixed, thanks!

**Comment by nojvspine** [comment]
Oh, nevermind, I opened nvim today and this error still persists
